name: zkuat

services:
  runtime:
    image: ghcr.io/rpetey317/zkuat-runtime:latest
    container_name: zkuat-runtime
    pull_policy: always
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.zkuat/runtime:/root/.zkuat/runtime
